### ISSUE TITLE
Add autoplay to videos

### ISSUE THREAD

**Issue by georgejphillips** [catchdigital/drupal-catchify#12]

**Comment by jjansoncatch** [comment]
There's a race condition (observed in chrome) where the YT video instance can have play/pause called before it's finished initialising. 
I think this could be fixed by polling to check init is done before trying to call play/pause. Possibly utilising the YT API and the `onReady` callback.
https://github.com/catchdigital/drupal-catchify/blob/c01ebf7ebec6ce728385b1ae15e119ee65e6895d/js/oembed/youtube.js#L22

**Comment by alberto115** [comment]
@jjansoncatch feel free to create a PR :)
